language: python
python:
  - '3.8'
  - '3.7'
  - '3.6'
  - '3.5'

install:
  - pip install setuptools tox pytest-cov

script:
  - tox

after_success:
  - "bash <(curl -s https://codecov.io/bash)"

jobs:
  include:
  - stage: build-docs
    install: pip install setuptools pdoc3 wrapt
    script:
      - pdoc3 -o docs --template-dir pdoc_tpl --html pyzkaccess
      - mv docs/pyzkaccess docs/api
    after_success: true  # https://travis-ci.community/t/does-skipping-everything-else-in-a-job-skip-deploy/6461/2
    deploy:
      provider: pages:git
      edge: true
      token: $GITHUB_TOKEN
      keep_history: true
      local_dir: docs
      target_branch: gh-pages
      on:
        tags: true
        branch: master
  - stage: deploy
    script: skip
    after_success: skip
    deploy:
      provider: pypi
      edge: true
      username: "__token__"
      password: $PYPI_TOKEN
      on:
        tags: true
        branch: master
